# Generated by Django 2.2.8 on 2020-10-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appawards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='posted_project',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user_bio',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user_name',
        ),
        migrations.AddField(
            model_name='image',
            name='live_link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='project_description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_bio',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
