# Generated by Django 2.2.8 on 2020-10-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appawards', '0002_auto_20201030_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='live_link',
            field=models.URLField(verbose_name='url'),
        ),
    ]
